
import sequelize from '../config/database.js';
import { Basecamp } from '../model/basecampmodel.js';

const dataBasecamp = [
{
    gunung_id: 58,
    name: "Kedah Desa Penosan Sepakat",
    elevation: null,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 159,
    name: "Pura Pasar Agung Bangli .",
    elevation: 1346,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 44,
    name: "Kersik Tuo Kerinci .",
    elevation: 1754,
    description: null,
    price_weekday: 18000,
    price_weekend: 23000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 218,
    name: "Sukamulya Purwakarta .",
    elevation: 625,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 60,
    name: "Palutungan Kuningan .",
    elevation: 1220,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 60,
    name: "Linggajati Kuningan .",
    elevation: 820,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 60,
    name: "Linggasana Kuningan .",
    elevation: 676,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 60,
    name: "Apuy Majalengka .",
    elevation: 1424,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 60,
    name: "Trisakti Sadarahe Majalengka .",
    elevation: 1288,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 153,
    name: "Babakan Jambuaer Sumedang .",
    elevation: 1128,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 130,
    name: "Legok Haji Cisarua .",
    elevation: 1224,
    description: null,
    price_weekday: 14000,
    price_weekend: 19000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 94,
    name: "Cipanganten Bandung .",
    elevation: 1857,
    description: null,
    price_weekday: 14000,
    price_weekend: 19000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 62,
    name: "Cibodas Cianjur .",
    elevation: 1386,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 62,
    name: "Gunung Putri Cianjur .",
    elevation: 1551,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 62,
    name: "Selabintana .",
    elevation: 960,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 107,
    name: "Citiis Tarogong Kaler Garut .",
    elevation: 804,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 107,
    name: "Cikahuripan Garut .",
    elevation: 1401,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 64,
    name: "Gunung Putri Cianjur .",
    elevation: 1551,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 64,
    name: "Cibodas Cianjur .",
    elevation: 1386,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 157,
    name: "Sawit Magelang .",
    elevation: 1319,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 157,
    name: "Gogik Magelang .",
    elevation: 1244,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 157,
    name: "Pendem Magelang .",
    elevation: 1290,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 112,
    name: "Desa Gumelem Pekalongan .",
    elevation: 1536,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 48,
    name: "Bambangan Purbalingga .",
    elevation: 1497,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 48,
    name: "Baturraden Purwokerto .",
    elevation: 900,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 48,
    name: "Kaliwadas Brebes .",
    elevation: 1771,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 48,
    name: "Dipajaya Pemalang .",
    elevation: 707,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 48,
    name: "Cemara Sakti Pemalang .",
    elevation: 1489,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 48,
    name: "Guci Tegal .",
    elevation: 1220,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 52,
    name: "Cemoro Sewu Magetan .",
    elevation: 1919,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 52,
    name: "Cemoro Kandang Karanganyar .",
    elevation: 1800,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 52,
    name: "Candi Cetho Karanganyar .",
    elevation: 1463,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 52,
    name: "Tambak Karanganyar .",
    elevation: 1158,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 52,
    name: "Singolangu Magetan .",
    elevation: 1327,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 98,
    name: "Sikunang Wonosobo .",
    elevation: 2066,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 98,
    name: "Ngandam Wonosobo .",
    elevation: 1859,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 98,
    name: "Silandak Wonosobo .",
    elevation: 1214,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 101,
    name: "Lengkong Wonosobo .",
    elevation: 1375,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 101,
    name: "Blembem Wonosobo .",
    elevation: 1344,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 63,
    name: "Selo Boyolali .",
    elevation: 1836,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 63,
    name: "Babadan Magelang .",
    elevation: 1263,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 63,
    name: "Sapuangin Klaten .",
    elevation: 1327,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 63,
    name: "Kinahrejo Sleman .",
    elevation: 1080,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 55,
    name: "Kledung Temanggung .",
    elevation: 1397,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 55,
    name: "Sigedang Wonosobo.",
    elevation: 1803,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 55,
    name: "Bansari Temanggung .",
    elevation: 1074,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 55,
    name: "Bedakah Wonosobo .",
    elevation: 1732,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 55,
    name: "Ndoro Arum  .",
    elevation: 1508,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 55,
    name: "Alang Alang Sewu Wonosobo .",
    elevation: 1344,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 49,
    name: "Mangli Magelang .",
    elevation: 1453,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 49,
    name: "Bowongso Wonosobo .",
    elevation: 1380,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 49,
    name: "Sipetung Temanggung .",
    elevation: 1279,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 49,
    name: "Garung Wonosobo .",
    elevation: 1440,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 49,
    name: "Butuh Temanggung .",
    elevation: 1701,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 49,
    name: "Banaran Temanggung .",
    elevation: 1174,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 129,
    name: "Mawar Camp Semarang .",
    elevation: 1278,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 129,
    name: "Perantunan Semarang .",
    elevation: 1287,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 129,
    name: "Promasan Semarang  .",
    elevation: 897,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 85,
    name: "Petakbanteng Wonosobo .",
    elevation: 1990,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 85,
    name: "Igirmanak Wonosobo .",
    elevation: 1755,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 85,
    name: "Wates Temanggung .",
    elevation: 1675,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 85,
    name: "Dwarawati Banjarnegara .",
    elevation: 2140,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 85,
    name: "Kalilembu Wonosobo .",
    elevation: 2065,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 85,
    name: "Dieng Wonosobo .",
    elevation: 2125,
    description: null,
    price_weekday: 10000,
    price_weekend: 15000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 56,
    name: "Selo Boyolali .",
    elevation: 1836,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 56,
    name: "Suwanting Magelang .",
    elevation: 1520,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 56,
    name: "Wekas Magelang .",
    elevation: 1781,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 56,
    name: "Cuntel Kopeng Semarang .",
    elevation: 1864,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 56,
    name: "Thekelan Semarang .",
    elevation: 1847,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 46,
    name: "Ranu Pane Lumajang .",
    elevation: 2113,
    description: null,
    price_weekday: 25000,
    price_weekend: 30000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 174,
    name: "Sumber Waru Bondowoso .",
    elevation: 597,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 50,
    name: "Kalibaru Banyuwangi .",
    elevation: 563,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 50,
    name: "Sumber Wringin Bondowoso .",
    elevation: 723,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 168,
    name: "Tamiajeng Mojokerto .",
    elevation: 690,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 168,
    name: "Jolotundo Mojokerto .",
    elevation: 705,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 168,
    name: "Kedungudi Mojokerto .",
    elevation: 598,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 154,
    name: "Karangrejo Blitar .",
    elevation: 442,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 154,
    name: "Tulungrejo Blitar .",
    elevation: 653,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 51,
    name: "Tambaksari Pasuruan .",
    elevation: 864,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 51,
    name: "Sumber Brantas Batu .",
    elevation: 2058,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 51,
    name: "Lawang Malang .",
    elevation: 892,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 51,
    name: "Tretes Pasuruan .",
    elevation: 793,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 59,
    name: "Bremi Probolinggo .",
    elevation: 908,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 59,
    name: "Baderan Situbondo .",
    elevation: 782,
    description: null,
    price_weekday: 13000,
    price_weekend: 18000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 103,
    name: "Tumbang Habangoi Katingan .",
    elevation: 92,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 103,
    name: "Rantau Malam Sintang .",
    elevation: 277,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 123,
    name: "Sidokatan Tanggamus .",
    elevation: 690,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 160,
    name: "Moya Ternate .",
    elevation: 288,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 45,
    name: "Sembalun Lombok Timur .",
    elevation: 1304,
    description: null,
    price_weekday: 30000,
    price_weekend: 35000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 45,
    name: "Torean Lombok Utara .",
    elevation: 556,
    description: null,
    price_weekday: 30000,
    price_weekend: 35000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 45,
    name: "Senaru Lombok Utara .",
    elevation: 774,
    description: null,
    price_weekday: 30000,
    price_weekend: 35000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 45,
    name: "Air Berik Lombok Tengah .",
    elevation: 579,
    description: null,
    price_weekday: 30000,
    price_weekend: 35000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 45,
    name: "Tetebatu Lombok Timur .",
    elevation: 907,
    description: null,
    price_weekday: 30000,
    price_weekend: 35000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 45,
    name: "Timbanuh Lombok Timur .",
    elevation: 830,
    description: null,
    price_weekday: 30000,
    price_weekend: 35000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 73,
    name: "Danau Tanralili Gowa .",
    elevation: 1166,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 73,
    name: "Lembanna Gowa .",
    elevation: 1500,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 77,
    name: "Manimbahoi .",
    elevation: 1261,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 47,
    name: "Karangan Enrekang .",
    elevation: 1442,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 47,
    name: "To'lajuk Latimojong .",
    elevation: 1146,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 70,
    name: "Tompobulu Gowa  .",
    elevation: 1619,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 84,
    name: "Air Batumbuk Solok .",
    elevation: 1455,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 84,
    name: "Batu Bajanjang Solok .",
    elevation: 1581,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 84,
    name: "Seroja Solok .",
    elevation: 1465,
    description: null,
    price_weekday: 12000,
    price_weekend: 17000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 53,
    name: "Tugu Rimau Pagar Alam .",
    elevation: 1847,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 53,
    name: "Balai Pendakian Kampung 4 Pagar Alam .",
    elevation: 1627,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 91,
    name: "Danau Lau Kawar Karo .",
    elevation: 1424,
    description: null,
    price_weekday: 20000,
    price_weekend: 25000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    gunung_id: 92,
    name: "Pancur Batu Karo .",
    elevation: 1517,
    description: null,
    price_weekday: 15000,
    price_weekend: 20000,
    camping_fee: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
}
];


async function seedBasecamp() {
  try {
    await sequelize.authenticate();
    console.log("Database connected");
    await sequelize.sync({ force: false });

    for (const basecamp of dataBasecamp) {
      await Basecamp.create(basecamp);
    }
    console.log("Basecamp data inserted");
    await sequelize.close();
  } catch (error) {
    console.error("Failed to seed basecamp data:", error);
  }
}

seedBasecamp();
